### ISSUE TITLE
crying as we speak

### ISSUE THREAD

**Issue by hecker12423** [LocalsGitHub/Discord-Logger-Builder#1]
C:\Users\golah\Discord-Logger-Builder>py builder.py
Loading, this may take a couple of minutes.
Traceback (most recent call last):
  File "C:\Users\golah\Discord-Logger-Builder\builder.py", line 25, in <module>
    exec("from alive_progress import alive_bar")
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'alive_progress'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\golah\Discord-Logger-Builder\builder.py", line 28, in <module>
    exec("from alive_progress import alive_bar")
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'alive_progress' what the dog doin?

**Comment by LocalsGitHub** [comment]
fix ur python installation. pip clearly isnt installed properly. uninstall all versions of python then reinstall python 3.8.6 and make sure pip is added onto path

**Comment by qualk** [comment]
[My](https://github.com/qualk/Discord-Logger-Builder) fork should fix that @hecker12423
